// 100+ trivia questions across 6 categories

export type Category = 'Science' | 'History' | 'Geography' | 'Sports' | 'Entertainment' | 'Technology'

export interface Question {
  category: Category
  question: string
  options: [string, string, string, string]
  correctIndex: 0 | 1 | 2 | 3
}

export const QUESTIONS: Question[] = [
  // ── Science (20 questions) ─────────────────────────────────────────────────
  {
    category: 'Science',
    question: 'What is the chemical symbol for gold?',
    options: ['Go', 'Gd', 'Au', 'Ag'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'How many bones are in the adult human body?',
    options: ['206', '198', '214', '256'],
    correctIndex: 0,
  },
  {
    category: 'Science',
    question: 'What planet is known as the Red Planet?',
    options: ['Venus', 'Jupiter', 'Saturn', 'Mars'],
    correctIndex: 3,
  },
  {
    category: 'Science',
    question: 'What is the speed of light in a vacuum (approx)?',
    options: ['300,000 km/s', '150,000 km/s', '450,000 km/s', '200,000 km/s'],
    correctIndex: 0,
  },
  {
    category: 'Science',
    question: 'Which gas makes up about 78% of Earth\'s atmosphere?',
    options: ['Oxygen', 'Carbon dioxide', 'Hydrogen', 'Nitrogen'],
    correctIndex: 3,
  },
  {
    category: 'Science',
    question: 'What is the atomic number of carbon?',
    options: ['6', '8', '12', '14'],
    correctIndex: 0,
  },
  {
    category: 'Science',
    question: 'Which organ produces insulin?',
    options: ['Liver', 'Kidney', 'Pancreas', 'Spleen'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Quartz', 'Diamond'],
    correctIndex: 3,
  },
  {
    category: 'Science',
    question: 'How many chromosomes does a typical human cell have?',
    options: ['23', '44', '46', '48'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'What force keeps planets in orbit around the Sun?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Electrostatics'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'What is the powerhouse of the cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Vacuole'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'Which planet has the most moons?',
    options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    correctIndex: 1,
  },
  {
    category: 'Science',
    question: 'What is H2O more commonly known as?',
    options: ['Hydrogen peroxide', 'Water', 'Hydrochloric acid', 'Saline'],
    correctIndex: 1,
  },
  {
    category: 'Science',
    question: 'What type of radiation has the highest frequency?',
    options: ['Radio waves', 'Microwaves', 'Gamma rays', 'Infrared'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'The theory of relativity was developed by whom?',
    options: ['Newton', 'Bohr', 'Tesla', 'Einstein'],
    correctIndex: 3,
  },
  {
    category: 'Science',
    question: 'What is the chemical formula for table salt?',
    options: ['NaCl', 'KCl', 'CaCO3', 'MgSO4'],
    correctIndex: 0,
  },
  {
    category: 'Science',
    question: 'Which element is represented by the symbol "Fe"?',
    options: ['Fluorine', 'Iron', 'Francium', 'Fermium'],
    correctIndex: 1,
  },
  {
    category: 'Science',
    question: 'What is the process by which plants make food using sunlight?',
    options: ['Respiration', 'Transpiration', 'Photosynthesis', 'Fermentation'],
    correctIndex: 2,
  },
  {
    category: 'Science',
    question: 'How many planets are in our solar system?',
    options: ['7', '8', '9', '10'],
    correctIndex: 1,
  },
  {
    category: 'Science',
    question: 'What is the nearest star to Earth?',
    options: ['Sirius', 'Betelgeuse', 'Proxima Centauri', 'The Sun'],
    correctIndex: 3,
  },

  // ── History (20 questions) ─────────────────────────────────────────────────
  {
    category: 'History',
    question: 'In which year did World War II end?',
    options: ['1943', '1944', '1945', '1946'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Who was the first US President?',
    options: ['John Adams', 'Thomas Jefferson', 'Benjamin Franklin', 'George Washington'],
    correctIndex: 3,
  },
  {
    category: 'History',
    question: 'The Berlin Wall fell in which year?',
    options: ['1987', '1988', '1989', '1991'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Which ancient wonder was located in Alexandria?',
    options: ['The Colossus', 'The Lighthouse', 'Hanging Gardens', 'The Mausoleum'],
    correctIndex: 1,
  },
  {
    category: 'History',
    question: 'Who painted the Mona Lisa?',
    options: ['Michelangelo', 'Raphael', 'Caravaggio', 'Leonardo da Vinci'],
    correctIndex: 3,
  },
  {
    category: 'History',
    question: 'The French Revolution began in which year?',
    options: ['1776', '1789', '1799', '1804'],
    correctIndex: 1,
  },
  {
    category: 'History',
    question: 'Who was the first person to walk on the Moon?',
    options: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'Alan Shepard'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'The Roman Empire fell (Western half) in which year?',
    options: ['410 AD', '455 AD', '476 AD', '500 AD'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Which empire was ruled by Genghis Khan?',
    options: ['Ottoman', 'Persian', 'Mongol', 'Ming'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Who wrote the Declaration of Independence?',
    options: ['John Adams', 'Benjamin Franklin', 'Thomas Jefferson', 'Alexander Hamilton'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'In which year did the Titanic sink?',
    options: ['1910', '1912', '1914', '1916'],
    correctIndex: 1,
  },
  {
    category: 'History',
    question: 'Which country was Napoleon Bonaparte born in?',
    options: ['France', 'Italy', 'Corsica', 'Spain'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'The Cold War was primarily between the US and which country?',
    options: ['China', 'Germany', 'USSR', 'North Korea'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Which pharaoh built the Great Pyramid of Giza?',
    options: ['Tutankhamun', 'Ramesses II', 'Khufu', 'Cleopatra'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'The Magna Carta was signed in which year?',
    options: ['1066', '1215', '1348', '1492'],
    correctIndex: 1,
  },
  {
    category: 'History',
    question: 'Who was the first woman to win a Nobel Prize?',
    options: ['Rosalind Franklin', 'Marie Curie', 'Florence Nightingale', 'Ada Lovelace'],
    correctIndex: 1,
  },
  {
    category: 'History',
    question: 'Which war was fought between the North and South of the USA?',
    options: ['Revolutionary War', 'War of 1812', 'Civil War', 'Spanish-American War'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Christopher Columbus sailed to the Americas in which year?',
    options: ['1488', '1490', '1492', '1498'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'The Cold War ended with the dissolution of the USSR in which year?',
    options: ['1989', '1990', '1991', '1993'],
    correctIndex: 2,
  },
  {
    category: 'History',
    question: 'Who was the first Emperor of Rome?',
    options: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'],
    correctIndex: 1,
  },

  // ── Geography (20 questions) ───────────────────────────────────────────────
  {
    category: 'Geography',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'Which is the longest river in the world?',
    options: ['Amazon', 'Mississippi', 'Yangtze', 'Nile'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'Mount Everest is located in which mountain range?',
    options: ['Andes', 'Rockies', 'Alps', 'Himalayas'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'Which country has the largest population?',
    options: ['USA', 'India', 'China', 'Indonesia'],
    correctIndex: 1,
  },
  {
    category: 'Geography',
    question: 'What is the smallest country in the world?',
    options: ['Monaco', 'San Marino', 'Liechtenstein', 'Vatican City'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'What is the capital of Japan?',
    options: ['Kyoto', 'Osaka', 'Tokyo', 'Hiroshima'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'The Sahara Desert is located on which continent?',
    options: ['Asia', 'South America', 'Australia', 'Africa'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'Which country has the most natural lakes?',
    options: ['Russia', 'USA', 'Canada', 'Brazil'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'What is the capital of Brazil?',
    options: ['Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'Which is the world\'s highest waterfall?',
    options: ['Niagara', 'Victoria', 'Iguazu', 'Angel Falls'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'How many continents are there on Earth?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'Which country shares the longest border with the USA?',
    options: ['Mexico', 'Canada', 'Cuba', 'Russia'],
    correctIndex: 1,
  },
  {
    category: 'Geography',
    question: 'The Amazon rainforest is primarily in which country?',
    options: ['Colombia', 'Peru', 'Venezuela', 'Brazil'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'What is the capital of South Africa?',
    options: ['Cape Town', 'Pretoria', 'Johannesburg', 'Durban'],
    correctIndex: 1,
  },
  {
    category: 'Geography',
    question: 'Which sea is the saltiest in the world?',
    options: ['Caspian Sea', 'Dead Sea', 'Red Sea', 'Black Sea'],
    correctIndex: 1,
  },
  {
    category: 'Geography',
    question: 'The Eiffel Tower is in which city?',
    options: ['Rome', 'Barcelona', 'Berlin', 'Paris'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'What is the largest desert in the world?',
    options: ['Sahara', 'Gobi', 'Arabian', 'Antarctic'],
    correctIndex: 3,
  },
  {
    category: 'Geography',
    question: 'Which country is known as the Land of the Rising Sun?',
    options: ['China', 'South Korea', 'Japan', 'Vietnam'],
    correctIndex: 2,
  },
  {
    category: 'Geography',
    question: 'What is the capital of Canada?',
    options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    correctIndex: 2,
  },

  // ── Sports (15 questions) ──────────────────────────────────────────────────
  {
    category: 'Sports',
    question: 'How many players are on a standard soccer team?',
    options: ['9', '10', '11', '12'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'Which country has won the most FIFA World Cups?',
    options: ['Germany', 'Argentina', 'Brazil', 'Italy'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'In basketball, how many points is a free throw worth?',
    options: ['1', '2', '3', '4'],
    correctIndex: 0,
  },
  {
    category: 'Sports',
    question: 'The Olympic Games originated in which country?',
    options: ['Italy', 'Greece', 'Egypt', 'Turkey'],
    correctIndex: 1,
  },
  {
    category: 'Sports',
    question: 'How many holes are in a standard round of golf?',
    options: ['12', '16', '18', '20'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'Which sport uses a shuttlecock?',
    options: ['Tennis', 'Squash', 'Badminton', 'Pickleball'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'In tennis, what does "love" mean?',
    options: ['30 points', '0 points', '15 points', '45 points'],
    correctIndex: 1,
  },
  {
    category: 'Sports',
    question: 'How many rings are on the Olympic flag?',
    options: ['4', '5', '6', '7'],
    correctIndex: 1,
  },
  {
    category: 'Sports',
    question: 'A marathon race is approximately how many miles?',
    options: ['20', '24', '26', '30'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'Which country invented basketball?',
    options: ['USA', 'Canada', 'UK', 'France'],
    correctIndex: 1,
  },
  {
    category: 'Sports',
    question: 'How many points is a touchdown worth in American football?',
    options: ['3', '4', '6', '7'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'Which sport is played at Wimbledon?',
    options: ['Cricket', 'Golf', 'Tennis', 'Polo'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'In boxing, how many rounds are in a world title fight?',
    options: ['10', '12', '15', '20'],
    correctIndex: 1,
  },
  {
    category: 'Sports',
    question: 'What shape is a standard soccer ball?',
    options: ['Cube', 'Oval', 'Sphere', 'Cylinder'],
    correctIndex: 2,
  },
  {
    category: 'Sports',
    question: 'How long is a standard Olympic swimming pool?',
    options: ['25m', '50m', '75m', '100m'],
    correctIndex: 1,
  },

  // ── Entertainment (15 questions) ──────────────────────────────────────────
  {
    category: 'Entertainment',
    question: 'Who played Iron Man in the Marvel Cinematic Universe?',
    options: ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo', 'Robert Downey Jr.'],
    correctIndex: 3,
  },
  {
    category: 'Entertainment',
    question: 'Which band recorded "Bohemian Rhapsody"?',
    options: ['Led Zeppelin', 'The Beatles', 'Queen', 'Pink Floyd'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'What fictional school does Harry Potter attend?',
    options: ['Durmstrang', 'Beauxbatons', 'Hogwarts', 'Castelobruxo'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'Which movie features the quote "I\'ll be back"?',
    options: ['RoboCop', 'Total Recall', 'The Terminator', 'Predator'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'What is the highest-grossing film of all time (as of 2023)?',
    options: ['Avengers: Endgame', 'Avatar', 'Titanic', 'Star Wars: The Force Awakens'],
    correctIndex: 1,
  },
  {
    category: 'Entertainment',
    question: 'Who sang "Thriller"?',
    options: ['Prince', 'Michael Jackson', 'David Bowie', 'Elton John'],
    correctIndex: 1,
  },
  {
    category: 'Entertainment',
    question: 'The TV show "Breaking Bad" is set in which US state?',
    options: ['Texas', 'Arizona', 'New Mexico', 'Colorado'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'Which streaming service produced "Stranger Things"?',
    options: ['HBO', 'Amazon', 'Disney+', 'Netflix'],
    correctIndex: 3,
  },
  {
    category: 'Entertainment',
    question: 'How many Oscars did Titanic (1997) win?',
    options: ['9', '10', '11', '14'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'Who wrote the novel "1984"?',
    options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Philip K. Dick'],
    correctIndex: 1,
  },
  {
    category: 'Entertainment',
    question: 'What color is the Incredible Hulk?',
    options: ['Blue', 'Red', 'Yellow', 'Green'],
    correctIndex: 3,
  },
  {
    category: 'Entertainment',
    question: 'Which country produces the most films annually?',
    options: ['USA', 'China', 'India', 'Japan'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'Who played James Bond the most times?',
    options: ['Sean Connery', 'Roger Moore', 'Daniel Craig', 'Pierce Brosnan'],
    correctIndex: 1,
  },
  {
    category: 'Entertainment',
    question: '"Game of Thrones" is based on novels by whom?',
    options: ['J.R.R. Tolkien', 'Terry Pratchett', 'George R.R. Martin', 'Robert Jordan'],
    correctIndex: 2,
  },
  {
    category: 'Entertainment',
    question: 'What instrument does Sherlock Holmes play?',
    options: ['Piano', 'Cello', 'Violin', 'Guitar'],
    correctIndex: 2,
  },

  // ── Technology (15 questions) ──────────────────────────────────────────────
  {
    category: 'Technology',
    question: 'Who co-founded Apple Inc.?',
    options: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'],
    correctIndex: 1,
  },
  {
    category: 'Technology',
    question: 'What does "HTTP" stand for?',
    options: ['HyperText Transfer Protocol', 'High Transfer Technology Process', 'HyperText Transport Program', 'Host Transfer Text Protocol'],
    correctIndex: 0,
  },
  {
    category: 'Technology',
    question: 'Which company created the Android operating system?',
    options: ['Apple', 'Microsoft', 'Google', 'Samsung'],
    correctIndex: 2,
  },
  {
    category: 'Technology',
    question: 'In binary, what does "1010" equal in decimal?',
    options: ['8', '9', '10', '12'],
    correctIndex: 2,
  },
  {
    category: 'Technology',
    question: 'What does "CPU" stand for?',
    options: ['Central Processing Unit', 'Core Power Unit', 'Computer Program Utility', 'Central Program Updater'],
    correctIndex: 0,
  },
  {
    category: 'Technology',
    question: 'Who invented the World Wide Web?',
    options: ['Vint Cerf', 'Tim Berners-Lee', 'Bill Gates', 'Steve Jobs'],
    correctIndex: 1,
  },
  {
    category: 'Technology',
    question: 'What programming language is known for its snake logo?',
    options: ['Ruby', 'Perl', 'Python', 'Go'],
    correctIndex: 2,
  },
  {
    category: 'Technology',
    question: 'Which company makes the iPhone?',
    options: ['Samsung', 'Google', 'Sony', 'Apple'],
    correctIndex: 3,
  },
  {
    category: 'Technology',
    question: 'What does "RAM" stand for?',
    options: ['Read Access Memory', 'Random Access Memory', 'Rapid Access Module', 'Runtime Application Memory'],
    correctIndex: 1,
  },
  {
    category: 'Technology',
    question: 'Who founded Tesla, Inc.?',
    options: ['Elon Musk', 'Martin Eberhard', 'JB Straubel', 'All of the above'],
    correctIndex: 3,
  },
  {
    category: 'Technology',
    question: 'What is the most popular programming language according to Stack Overflow 2023?',
    options: ['Python', 'JavaScript', 'Java', 'TypeScript'],
    correctIndex: 1,
  },
  {
    category: 'Technology',
    question: 'What does "AI" stand for?',
    options: ['Automatic Input', 'Advanced Interface', 'Artificial Intelligence', 'Automated Integration'],
    correctIndex: 2,
  },
  {
    category: 'Technology',
    question: 'Which company created the PostgreSQL database?',
    options: ['Oracle', 'Microsoft', 'PostgreSQL Global Development Group', 'IBM'],
    correctIndex: 2,
  },
  {
    category: 'Technology',
    question: 'What is the file extension for a TypeScript file?',
    options: ['.js', '.ts', '.tsx', '.type'],
    correctIndex: 1,
  },
  {
    category: 'Technology',
    question: 'Which protocol is used to send email?',
    options: ['FTP', 'SSH', 'SMTP', 'HTTP'],
    correctIndex: 2,
  },
]
